from pymongo import MongoClient
import json

class DatabaseManager:
    def __init__(self, db_name):
        self.db_client = MongoClient(db_name).test

    def insert_enpleadoselectronica(self, empleados):
        self.db_client.casas.insert_many(empleados)

empleados = []
pathBBDD = "mongodb+srv://fpratsquilez:GTdbIFamKljeyUvs@worldmanagergame.k3rozlq.mongodb.net/?retryWrites=true&w=majority"


empleados = [
{
    "id": 1,
    "nombre_casa": "Casa Serenidad",
    "nombre_ciudad": "Jumilla",
    "precio": 90000,
    "prestigio": 6,
    "propietario": "Libre",
    "coordenadas_x": 38.479835,
    "coordenadas_y": -1.320958,
    "seguridad": 0
  },
  {
    "id": 2,
    "nombre_casa": "Villa Esmeralda",
    "nombre_ciudad": "Jumilla",
    "precio": 120000,
    "prestigio": 8,
    "propietario": "Libre",
    "coordenadas_x": 38.481267,
    "coordenadas_y": -1.316407,
    "seguridad": 0
  },
  {
    "id": 3,
    "nombre_casa": "Refugio del Sol",
    "nombre_ciudad": "Jumilla",
    "precio": 60000,
    "prestigio": 4,
    "propietario": "Libre",
    "coordenadas_x": 38.476493,
    "coordenadas_y": -1.318634,
    "seguridad": 0
  },
  {
    "id": 4,
    "nombre_casa": "Quinta Luna",
    "nombre_ciudad": "Jumilla",
    "precio": 75000,
    "prestigio": 5,
    "propietario": "Libre",
    "coordenadas_x": 38.478907,
    "coordenadas_y": -1.322579,
    "seguridad": 0
  },
  {
    "id": 5,
    "nombre_casa": "Hogar Dulce Hogar",
    "nombre_ciudad": "Jumilla",
    "precio": 80000,
    "prestigio": 5,
    "propietario": "Libre",
    "coordenadas_x": 38.477612,
    "coordenadas_y": -1.319857,
    "seguridad": 0
  },
  {
    "id": 6,
    "nombre_casa": "Casa Encanto",
    "nombre_ciudad": "Jumilla",
    "precio": 110000,
    "prestigio": 7,
    "propietario": "Libre",
    "coordenadas_x": 38.479405,
    "coordenadas_y": -1.318113,
    "seguridad": 0
  },
  {
    "id": 7,
    "nombre_casa": "Mansión Aurora",
    "nombre_ciudad": "Jumilla",
    "precio": 140000,
    "prestigio": 9,
    "propietario": "Libre",
    "coordenadas_x": 38.478202,
    "coordenadas_y": -1.317229,
    "seguridad": 0
  },
  {
    "id": 8,
    "nombre_casa": "Villa del Sol",
    "nombre_ciudad": "Jumilla",
    "precio": 130000,
    "prestigio": 8,
    "propietario": "Libre",
    "coordenadas_x": 38.479991,
    "coordenadas_y": -1.321308,
    "seguridad": 0
  },
  {
    "id": 9,
    "nombre_casa": "Rincón Acogedor",
    "nombre_ciudad": "Jumilla",
    "precio": 70000,
    "prestigio": 4,
    "propietario": "Libre",
    "coordenadas_x": 38.480785,
    "coordenadas_y": -1.319553,
    "seguridad": 0
  },
  {
    "id": 10,
    "nombre_casa": "Pequeño Refugio",
    "nombre_ciudad": "Jumilla",
    "precio": 50000,
    "prestigio": 3,
    "propietario": "Libre",
    "coordenadas_x": 38.478334,
    "coordenadas_y": -1.318134,
    "seguridad": 0
  },
    {
    "id": 1,
    "nombre_casa": "Casa Serenidad",
    "nombre_ciudad": "Baeza",
    "precio": 90000,
    "prestigio": 6,
    "propietario": "Libre",
    "coordenadas_x": 37.995185,
    "coordenadas_y": -3.467648,
    "seguridad": 0
  },
  {
    "id": 2,
    "nombre_casa": "Villa Esmeralda",
    "nombre_ciudad": "Baeza",
    "precio": 120000,
    "prestigio": 8,
    "propietario": "Libre",
    "coordenadas_x": 37.999431,
    "coordenadas_y": -3.462722,
    "seguridad": 0
  },
  {
    "id": 3,
    "nombre_casa": "Refugio del Sol",
    "nombre_ciudad": "Baeza",
    "precio": 60000,
    "prestigio": 4,
    "propietario": "Libre",
    "coordenadas_x": 37.993765,
    "coordenadas_y": -3.465925,
    "seguridad": 0
  },
  {
    "id": 4,
    "nombre_casa": "Quinta Luna",
    "nombre_ciudad": "Baeza",
    "precio": 75000,
    "prestigio": 5,
    "propietario": "Libre",
    "coordenadas_x": 37.997827,
    "coordenadas_y": -3.468936,
    "seguridad": 0
  },
  {
    "id": 5,
    "nombre_casa": "Hogar Dulce Hogar",
    "nombre_ciudad": "Baeza",
    "precio": 80000,
    "prestigio": 5,
    "propietario": "Libre",
    "coordenadas_x": 37.996229,
    "coordenadas_y": -3.466502,
    "seguridad": 0
  },
  {
    "id": 6,
    "nombre_casa": "Casa Encanto",
    "nombre_ciudad": "Baeza",
    "precio": 110000,
    "prestigio": 7,
    "propietario": "Libre",
    "coordenadas_x": 37.998448,
    "coordenadas_y": -3.464328,
    "seguridad": 0
  },
  {
    "id": 7,
    "nombre_casa": "Mansión Aurora",
    "nombre_ciudad": "Baeza",
    "precio": 140000,
    "prestigio": 9,
    "propietario": "Libre",
    "coordenadas_x": 37.994986,
    "coordenadas_y": -3.463322,
    "seguridad": 0
  },
  {
    "id": 8,
    "nombre_casa": "Villa del Sol",
    "nombre_ciudad": "Baeza",
    "precio": 130000,
    "prestigio": 8,
    "propietario": "Libre",
    "coordenadas_x": 38.000234,
    "coordenadas_y": -3.461249,
    "seguridad": 0
  },
  {
    "id": 9,
    "nombre_casa": "Rincón Acogedor",
    "nombre_ciudad": "Baeza",
    "precio": 70000,
    "prestigio": 4,
    "propietario": "Libre",
    "coordenadas_x": 37.996890,
    "coordenadas_y": -3.464860,
    "seguridad": 0
  },
  {
    "id": 10,
    "nombre_casa": "Pequeño Refugio",
    "nombre_ciudad": "Baeza",
    "precio": 50000,
    "prestigio": 3,
    "propietario": "Libre",
    "coordenadas_x": 37.995546,
    "coordenadas_y": -3.467176,
    "seguridad": 0
  },
    {
    "id": 1,
    "nombre_casa": "Casa Serenidad",
    "nombre_ciudad": "Ulldecona",
    "precio": 90000,
    "prestigio": 6,
    "propietario": "Libre",
    "coordenadas_x": 40.564859,
    "coordenadas_y": 0.489376,
    "seguridad": 0
  },
  {
    "id": 2,
    "nombre_casa": "Villa Esmeralda",
    "nombre_ciudad": "Ulldecona",
    "precio": 120000,
    "prestigio": 8,
    "propietario": "Libre",
    "coordenadas_x": 40.571297,
    "coordenadas_y": 0.481462,
    "seguridad": 0
  },
  {
    "id": 3,
    "nombre_casa": "Refugio del Sol",
    "nombre_ciudad": "Ulldecona",
    "precio": 60000,
    "prestigio": 4,
    "propietario": "Libre",
    "coordenadas_x": 40.570011,
    "coordenadas_y": 0.485245,
    "seguridad": 0
  },
  {
    "id": 4,
    "nombre_casa": "Quinta Luna",
    "nombre_ciudad": "Ulldecona",
    "precio": 75000,
    "prestigio": 5,
    "propietario": "Libre",
    "coordenadas_x": 40.568693,
    "coordenadas_y": 0.483931,
    "seguridad": 0
  },
  {
    "id": 5,
    "nombre_casa": "Hogar Dulce Hogar",
    "nombre_ciudad": "Ulldecona",
    "precio": 80000,
    "prestigio": 5,
    "propietario": "Libre",
    "coordenadas_x": 40.572165,
    "coordenadas_y": 0.486372,
    "seguridad": 0
  },
  {
    "id": 6,
    "nombre_casa": "Casa Encanto",
    "nombre_ciudad": "Ulldecona",
    "precio": 110000,
    "prestigio": 7,
    "propietario": "Libre",
    "coordenadas_x": 40.569745,
    "coordenadas_y": 0.484528,
    "seguridad": 0
  },
  {
    "id": 7,
    "nombre_casa": "Mansión Aurora",
    "nombre_ciudad": "Ulldecona",
    "precio": 140000,
    "prestigio": 9,
    "propietario": "Libre",
    "coordenadas_x": 40.568075,
    "coordenadas_y": 0.485821,
    "seguridad": 0
  },
  {
    "id": 8,
    "nombre_casa": "Villa del Sol",
    "nombre_ciudad": "Ulldecona",
    "precio": 130000,
    "prestigio": 8,
    "propietario": "Libre",
    "coordenadas_x": 40.570921,
    "coordenadas_y": 0.484632,
    "seguridad": 0
  },
  {
    "id": 9,
    "nombre_casa": "Rincón Acogedor",
    "nombre_ciudad": "Ulldecona",
    "precio": 70000,
    "prestigio": 4,
    "propietario": "Libre",
    "coordenadas_x": 40.571788,
    "coordenadas_y": 0.485982,
    "seguridad": 0
  },
  {
    "id": 10,
    "nombre_casa": "Pequeño Refugio",
    "nombre_ciudad": "Ulldecona",
    "precio": 50000,
    "prestigio": 3,
    "propietario": "Libre",
    "coordenadas_x": 40.567983,
    "coordenadas_y": 0.484158,
    "seguridad": 0
  },
    {
    "id": 1,
    "nombre_casa": "Casa Serenidad",
    "nombre_ciudad": "La Roda",
    "precio": 120000,
    "prestigio": 8,
    "propietario": "Libre",
    "coordenadas_x": 39.216743,
    "coordenadas_y": -2.149245,
    "seguridad": 0
  },
  {
    "id": 2,
    "nombre_casa": "Villa Esmeralda",
    "nombre_ciudad": "La Roda",
    "precio": 140000,
    "prestigio": 9,
    "propietario": "Libre",
    "coordenadas_x": 39.220839,
    "coordenadas_y": -2.148682,
    "seguridad": 0
  },
  {
    "id": 3,
    "nombre_casa": "Refugio del Sol",
    "nombre_ciudad": "La Roda",
    "precio": 90000,
    "prestigio": 6,
    "propietario": "Libre",
    "coordenadas_x": 39.221615,
    "coordenadas_y": -2.150867,
    "seguridad": 0
  },
  {
    "id": 4,
    "nombre_casa": "Quinta Luna",
    "nombre_ciudad": "La Roda",
    "precio": 110000,
    "prestigio": 7,
    "propietario": "Libre",
    "coordenadas_x": 39.216309,
    "coordenadas_y": -2.148451,
    "seguridad": 0
  },
  {
    "id": 5,
    "nombre_casa": "Hogar Dulce Hogar",
    "nombre_ciudad": "La Roda",
    "precio": 100000,
    "prestigio": 7,
    "propietario": "Libre",
    "coordenadas_x": 39.219043,
    "coordenadas_y": -2.149358,
    "seguridad": 0
  },
  {
    "id": 6,
    "nombre_casa": "Casa Encanto",
    "nombre_ciudad": "La Roda",
    "precio": 130000,
    "prestigio": 8,
    "propietario": "Libre",
    "coordenadas_x": 39.221143,
    "coordenadas_y": -2.151791,
    "seguridad": 0
  },
  {
    "id": 7,
    "nombre_casa": "Mansión Aurora",
    "nombre_ciudad": "La Roda",
    "precio": 150000,
    "prestigio": 10,
    "propietario": "Libre",
    "coordenadas_x": 39.218603,
    "coordenadas_y": -2.149942,
    "seguridad": 0
  },
  {
    "id": 8,
    "nombre_casa": "Villa del Sol",
    "nombre_ciudad": "La Roda",
    "precio": 140000,
    "prestigio": 9,
    "propietario": "Libre",
    "coordenadas_x": 39.220488,
    "coordenadas_y": -2.150684,
    "seguridad": 0
  },
  {
    "id": 9,
    "nombre_casa": "Rincón Acogedor",
    "nombre_ciudad": "La Roda",
    "precio": 80000,
    "prestigio": 5,
    "propietario": "Libre",
    "coordenadas_x": 39.217536,
    "coordenadas_y": -2.149192,
    "seguridad": 0
  },
  {
    "id": 10,
    "nombre_casa": "Pequeño Refugio",
    "nombre_ciudad": "La Roda",
    "precio": 70000,
    "prestigio": 4,
    "propietario": "Libre",
    "coordenadas_x": 39.219953,
    "coordenadas_y": -2.151345,
    "seguridad": 0
  },
    {
    "id": 1,
    "nombre_casa": "Casa Serenidad",
    "nombre_ciudad": "Tazacorte",
    "precio": 90000,
    "prestigio": 6,
    "propietario": "Libre",
    "coordenadas_x": 28.637424,
    "coordenadas_y": -17.937040,
    "seguridad": 0
  },
  {
    "id": 2,
    "nombre_casa": "Villa Esmeralda",
    "nombre_ciudad": "Tazacorte",
    "precio": 120000,
    "prestigio": 8,
    "propietario": "Libre",
    "coordenadas_x": 28.638571,
    "coordenadas_y": -17.935919,
    "seguridad": 0
  },
  {
    "id": 3,
    "nombre_casa": "Refugio del Sol",
    "nombre_ciudad": "Tazacorte",
    "precio": 60000,
    "prestigio": 4,
    "propietario": "Libre",
    "coordenadas_x": 28.637784,
    "coordenadas_y": -17.938301,
    "seguridad": 0
  },
  {
    "id": 4,
    "nombre_casa": "Quinta Luna",
    "nombre_ciudad": "Tazacorte",
    "precio": 75000,
    "prestigio": 5,
    "propietario": "Libre",
    "coordenadas_x": 28.638919,
    "coordenadas_y": -17.937138,
    "seguridad": 0
  },
  {
    "id": 5,
    "nombre_casa": "Hogar Dulce Hogar",
    "nombre_ciudad": "Tazacorte",
    "precio": 80000,
    "prestigio": 5,
    "propietario": "Libre",
    "coordenadas_x": 28.636907,
    "coordenadas_y": -17.936255,
    "seguridad": 0
  },
  {
    "id": 6,
    "nombre_casa": "Casa Encanto",
    "nombre_ciudad": "Tazacorte",
    "precio": 110000,
    "prestigio": 7,
    "propietario": "Libre",
    "coordenadas_x": 28.636217,
    "coordenadas_y": -17.938176,
    "seguridad": 0
  },
  {
    "id": 7,
    "nombre_casa": "Mansión Aurora",
    "nombre_ciudad": "Tazacorte",
    "precio": 140000,
    "prestigio": 9,
    "propietario": "Libre",
    "coordenadas_x": 28.637146,
    "coordenadas_y": -17.935657,
    "seguridad": 0
  },
  {
    "id": 8,
    "nombre_casa": "Villa del Sol",
    "nombre_ciudad": "Tazacorte",
    "precio": 130000,
    "prestigio": 8,
    "propietario": "Libre",
    "coordenadas_x": 28.638252,
    "coordenadas_y": -17.937625,
    "seguridad": 0
  },
  {
    "id": 9,
    "nombre_casa": "Rincón Acogedor",
    "nombre_ciudad": "Tazacorte",
    "precio": 70000,
    "prestigio": 4,
    "propietario": "Libre",
    "coordenadas_x": 28.635659,
    "coordenadas_y": -17.936895,
    "seguridad": 0
  },
  {
    "id": 10,
    "nombre_casa": "Pequeño Refugio",
    "nombre_ciudad": "Tazacorte",
    "precio": 50000,
    "prestigio": 3,
    "propietario": "Libre",
    "coordenadas_x": 28.637818,
    "coordenadas_y": -17.938020,
    "seguridad": 0
  },
    {
    "id": 1,
    "nombre_casa": "Casa Serenidad",
    "nombre_ciudad": "Calahorra",
    "precio": 90000,
    "prestigio": 6,
    "propietario": "Libre",
    "coordenadas_x": 42.301789,
    "coordenadas_y": -1.959166,
    "seguridad": 0
  },
  {
    "id": 2,
    "nombre_casa": "Villa Esmeralda",
    "nombre_ciudad": "Calahorra",
    "precio": 120000,
    "prestigio": 8,
    "propietario": "Libre",
    "coordenadas_x": 42.300548,
    "coordenadas_y": -1.961062,
    "seguridad": 0
  },
  {
    "id": 3,
    "nombre_casa": "Refugio del Sol",
    "nombre_ciudad": "Calahorra",
    "precio": 60000,
    "prestigio": 4,
    "propietario": "Libre",
    "coordenadas_x": 42.299274,
    "coordenadas_y": -1.960395,
    "seguridad": 0
  },
  {
    "id": 4,
    "nombre_casa": "Quinta Luna",
    "nombre_ciudad": "Calahorra",
    "precio": 75000,
    "prestigio": 5,
    "propietario": "Libre",
    "coordenadas_x": 42.301074,
    "coordenadas_y": -1.959981,
    "seguridad": 0
  },
  {
    "id": 5,
    "nombre_casa": "Hogar Dulce Hogar",
    "nombre_ciudad": "Calahorra",
    "precio": 80000,
    "prestigio": 5,
    "propietario": "Libre",
    "coordenadas_x": 42.298624,
    "coordenadas_y": -1.961742,
    "seguridad": 0
  },
  {
    "id": 6,
    "nombre_casa": "Casa Encanto",
    "nombre_ciudad": "Calahorra",
    "precio": 110000,
    "prestigio": 7,
    "propietario": "Libre",
    "coordenadas_x": 42.298980,
    "coordenadas_y": -1.959730,
    "seguridad": 0
  },
  {
    "id": 7,
    "nombre_casa": "Mansión Aurora",
    "nombre_ciudad": "Calahorra",
    "precio": 140000,
    "prestigio": 9,
    "propietario": "Libre",
    "coordenadas_x": 42.300981,
    "coordenadas_y": -1.960537,
    "seguridad": 0
  },
  {
    "id": 8,
    "nombre_casa": "Villa del Sol",
    "nombre_ciudad": "Calahorra",
    "precio": 130000,
    "prestigio": 8,
    "propietario": "Libre",
    "coordenadas_x": 42.299862,
    "coordenadas_y": -1.960229,
    "seguridad": 0
  },
  {
    "id": 9,
    "nombre_casa": "Rincón Acogedor",
    "nombre_ciudad": "Calahorra",
    "precio": 70000,
    "prestigio": 4,
    "propietario": "Libre",
    "coordenadas_x": 42.301266,
    "coordenadas_y": -1.961309,
    "seguridad": 0
  },
  {
    "id": 10,
    "nombre_casa": "Pequeño Refugio",
    "nombre_ciudad": "Calahorra",
    "precio": 50000,
    "prestigio": 3,
    "propietario": "Libre",
    "coordenadas_x": 42.298363,
    "coordenadas_y": -1.959951,
    "seguridad": 0
  },
    {
    "id": 1,
    "nombre_casa": "Casa Serenidad",
    "nombre_ciudad": "Reus",
    "precio": 90000,
    "prestigio": 6,
    "propietario": "Libre",
    "coordenadas_x": 41.157746,
    "coordenadas_y": 1.106587,
    "seguridad": 0
  },
  {
    "id": 2,
    "nombre_casa": "Villa Esmeralda",
    "nombre_ciudad": "Reus",
    "precio": 120000,
    "prestigio": 8,
    "propietario": "Libre",
    "coordenadas_x": 41.155892,
    "coordenadas_y": 1.108539,
    "seguridad": 0
  },
  {
    "id": 3,
    "nombre_casa": "Refugio del Sol",
    "nombre_ciudad": "Reus",
    "precio": 60000,
    "prestigio": 4,
    "propietario": "Libre",
    "coordenadas_x": 41.158682,
    "coordenadas_y": 1.108247,
    "seguridad": 0
  },
  {
    "id": 4,
    "nombre_casa": "Quinta Luna",
    "nombre_ciudad": "Reus",
    "precio": 75000,
    "prestigio": 5,
    "propietario": "Libre",
    "coordenadas_x": 41.157187,
    "coordenadas_y": 1.109399,
    "seguridad": 0
  },
  {
    "id": 5,
    "nombre_casa": "Hogar Dulce Hogar",
    "nombre_ciudad": "Reus",
    "precio": 80000,
    "prestigio": 5,
    "propietario": "Libre",
    "coordenadas_x": 41.156329,
    "coordenadas_y": 1.107998,
    "seguridad": 0
  },
  {
    "id": 6,
    "nombre_casa": "Casa Encanto",
    "nombre_ciudad": "Reus",
    "precio": 110000,
    "prestigio": 7,
    "propietario": "Libre",
    "coordenadas_x": 41.158427,
    "coordenadas_y": 1.109672,
    "seguridad": 0
  },
  {
    "id": 7,
    "nombre_casa": "Mansión Aurora",
    "nombre_ciudad": "Reus",
    "precio": 140000,
    "prestigio": 9,
    "propietario": "Libre",
    "coordenadas_x": 41.155671,
    "coordenadas_y": 1.110657,
    "seguridad": 0
  },
  {
    "id": 8,
    "nombre_casa": "Villa del Sol",
    "nombre_ciudad": "Reus",
    "precio": 130000,
    "prestigio": 8,
    "propietario": "Libre",
    "coordenadas_x": 41.157984,
    "coordenadas_y": 1.109984,
    "seguridad": 0
  },
  {
    "id": 9,
    "nombre_casa": "Rincón Acogedor",
    "nombre_ciudad": "Reus",
    "precio": 70000,
    "prestigio": 4,
    "propietario": "Libre",
    "coordenadas_x": 41.157432,
    "coordenadas_y": 1.110287,
    "seguridad": 0
  },
  {
    "id": 10,
    "nombre_casa": "Pequeño Refugio",
    "nombre_ciudad": "Reus",
    "precio": 50000,
    "prestigio": 3,
    "propietario": "Libre",
    "coordenadas_x": 41.156716,
    "coordenadas_y": 1.108601,
    "seguridad": 0
  },
    {
    "id": 1,
    "nombre_casa": "Casa Serenidad",
    "nombre_ciudad": "Tordesillas",
    "precio": 90000,
    "prestigio": 6,
    "propietario": "Libre",
    "coordenadas_x": 41.504295,
    "coordenadas_y": -4.936351,
    "seguridad": 0
  },
  {
    "id": 2,
    "nombre_casa": "Villa Esmeralda",
    "nombre_ciudad": "Tordesillas",
    "precio": 120000,
    "prestigio": 8,
    "propietario": "Libre",
    "coordenadas_x": 41.503662,
    "coordenadas_y": -4.935579,
    "seguridad": 0
  },
  {
    "id": 3,
    "nombre_casa": "Refugio del Sol",
    "nombre_ciudad": "Tordesillas",
    "precio": 60000,
    "prestigio": 4,
    "propietario": "Libre",
    "coordenadas_x": 41.503156,
    "coordenadas_y": -4.937046,
    "seguridad": 0
  },
  {
    "id": 4,
    "nombre_casa": "Quinta Luna",
    "nombre_ciudad": "Tordesillas",
    "precio": 75000,
    "prestigio": 5,
    "propietario": "Libre",
    "coordenadas_x": 41.502419,
    "coordenadas_y": -4.936064,
    "seguridad": 0
  },
  {
    "id": 5,
    "nombre_casa": "Hogar Dulce Hogar",
    "nombre_ciudad": "Tordesillas",
    "precio": 80000,
    "prestigio": 5,
    "propietario": "Libre",
    "coordenadas_x": 41.502853,
    "coordenadas_y": -4.935239,
    "seguridad": 0
  },
  {
    "id": 6,
    "nombre_casa": "Casa Encanto",
    "nombre_ciudad": "Tordesillas",
    "precio": 110000,
    "prestigio": 7,
    "propietario": "Libre",
    "coordenadas_x": 41.504151,
    "coordenadas_y": -4.936716,
    "seguridad": 0
  },
  {
    "id": 7,
    "nombre_casa": "Mansión Aurora",
    "nombre_ciudad": "Tordesillas",
    "precio": 140000,
    "prestigio": 9,
    "propietario": "Libre",
    "coordenadas_x": 41.503745,
    "coordenadas_y": -4.935924,
    "seguridad": 0
  },
  {
    "id": 8,
    "nombre_casa": "Villa del Sol",
    "nombre_ciudad": "Tordesillas",
    "precio": 130000,
    "prestigio": 8,
    "propietario": "Libre",
    "coordenadas_x": 41.502980,
    "coordenadas_y": -4.935556,
    "seguridad": 0
  },
  {
    "id": 9,
    "nombre_casa": "Rincón Acogedor",
    "nombre_ciudad": "Tordesillas",
    "precio": 70000,
    "prestigio": 4,
    "propietario": "Libre",
    "coordenadas_x": 41.503862,
    "coordenadas_y": -4.936290,
    "seguridad": 0
  },
  {
    "id": 10,
    "nombre_casa": "Pequeño Refugio",
    "nombre_ciudad": "Tordesillas",
    "precio": 50000,
    "prestigio": 3,
    "propietario": "Libre",
    "coordenadas_x": 41.503355,
    "coordenadas_y": -4.937123,
    "seguridad": 0
  },
    {
    "id": 1,
    "nombre_casa": "Casa Serenidad",
    "nombre_ciudad": "El Ejido",
    "precio": 90000,
    "prestigio": 6,
    "propietario": "Libre",
    "coordenadas_x": 36.773856,
    "coordenadas_y": -2.811381,
    "seguridad": 0
  },
  {
    "id": 2,
    "nombre_casa": "Villa Esmeralda",
    "nombre_ciudad": "El Ejido",
    "precio": 120000,
    "prestigio": 8,
    "propietario": "Libre",
    "coordenadas_x": 36.770514,
    "coordenadas_y": -2.815524,
    "seguridad": 0
  },
  {
    "id": 3,
    "nombre_casa": "Refugio del Sol",
    "nombre_ciudad": "El Ejido",
    "precio": 60000,
    "prestigio": 4,
    "propietario": "Libre",
    "coordenadas_x": 36.770961,
    "coordenadas_y": -2.812994,
    "seguridad": 0
  },
  {
    "id": 4,
    "nombre_casa": "Quinta Luna",
    "nombre_ciudad": "El Ejido",
    "precio": 75000,
    "prestigio": 5,
    "propietario": "Libre",
    "coordenadas_x": 36.772430,
    "coordenadas_y": -2.814459,
    "seguridad": 0
  },
  {
    "id": 5,
    "nombre_casa": "Hogar Dulce Hogar",
    "nombre_ciudad": "El Ejido",
    "precio": 80000,
    "prestigio": 5,
    "propietario": "Libre",
    "coordenadas_x": 36.772901,
    "coordenadas_y": -2.815887,
    "seguridad": 0
  },
  {
    "id": 6,
    "nombre_casa": "Casa Encanto",
    "nombre_ciudad": "El Ejido",
    "precio": 110000,
    "prestigio": 7,
    "propietario": "Libre",
    "coordenadas_x": 36.771860,
    "coordenadas_y": -2.815332,
    "seguridad": 0
  },
  {
    "id": 7,
    "nombre_casa": "Mansión Aurora",
    "nombre_ciudad": "El Ejido",
    "precio": 140000,
    "prestigio": 9,
    "propietario": "Libre",
    "coordenadas_x": 36.772540,
    "coordenadas_y": -2.811994,
    "seguridad": 0
  },
  {
    "id": 8,
    "nombre_casa": "Villa del Sol",
    "nombre_ciudad": "El Ejido",
    "precio": 130000,
    "prestigio": 8,
    "propietario": "Libre",
    "coordenadas_x": 36.771293,
    "coordenadas_y": -2.813016,
    "seguridad": 0
  },
  {
    "id": 9,
    "nombre_casa": "Rincón Acogedor",
    "nombre_ciudad": "El Ejido",
    "precio": 70000,
    "prestigio": 4,
    "propietario": "Libre",
    "coordenadas_x": 36.773110,
    "coordenadas_y": -2.812727,
    "seguridad": 0
  },
  {
    "id": 10,
    "nombre_casa": "Pequeño Refugio",
    "nombre_ciudad": "El Ejido",
    "precio": 50000,
    "prestigio": 3,
    "propietario": "Libre",
    "coordenadas_x": 36.771615,
    "coordenadas_y": -2.815015,
    "seguridad": 0
  },
    {
    "id": 1,
    "nombre_casa": "Casa Serenidad",
    "nombre_ciudad": "Lepe",
    "precio": 90000,
    "prestigio": 6,
    "propietario": "Libre",
    "coordenadas_x": 37.250392,
    "coordenadas_y": -7.210702,
    "seguridad": 0
  },
  {
    "id": 2,
    "nombre_casa": "Villa Esmeralda",
    "nombre_ciudad": "Lepe",
    "precio": 120000,
    "prestigio": 8,
    "propietario": "Libre",
    "coordenadas_x": 37.254074,
    "coordenadas_y": -7.208891,
    "seguridad": 0
  },
  {
    "id": 3,
    "nombre_casa": "Refugio del Sol",
    "nombre_ciudad": "Lepe",
    "precio": 60000,
    "prestigio": 4,
    "propietario": "Libre",
    "coordenadas_x": 37.249712,
    "coordenadas_y": -7.208053,
    "seguridad": 0
  },
  {
    "id": 4,
    "nombre_casa": "Quinta Luna",
    "nombre_ciudad": "Lepe",
    "precio": 75000,
    "prestigio": 5,
    "propietario": "Libre",
    "coordenadas_x": 37.252903,
    "coordenadas_y": -7.212177,
    "seguridad": 0
  },
  {
    "id": 5,
    "nombre_casa": "Hogar Dulce Hogar",
    "nombre_ciudad": "Lepe",
    "precio": 80000,
    "prestigio": 5,
    "propietario": "Libre",
    "coordenadas_x": 37.250909,
    "coordenadas_y": -7.210376,
    "seguridad": 0
  },
  {
    "id": 6,
    "nombre_casa": "Casa Encanto",
    "nombre_ciudad": "Lepe",
    "precio": 110000,
    "prestigio": 7,
    "propietario": "Libre",
    "coordenadas_x": 37.251672,
    "coordenadas_y": -7.211738,
    "seguridad": 0
  },
  {
    "id": 7,
    "nombre_casa": "Mansión Aurora",
    "nombre_ciudad": "Lepe",
    "precio": 140000,
    "prestigio": 9,
    "propietario": "Libre",
    "coordenadas_x": 37.251032,
    "coordenadas_y": -7.211076,
    "seguridad": 0
  },
  {
    "id": 8,
    "nombre_casa": "Villa del Sol",
    "nombre_ciudad": "Lepe",
    "precio": 130000,
    "prestigio": 8,
    "propietario": "Libre",
    "coordenadas_x": 37.252240,
    "coordenadas_y": -7.210002,
    "seguridad": 0
  },
  {
    "id": 9,
    "nombre_casa": "Rincón Acogedor",
    "nombre_ciudad": "Lepe",
    "precio": 70000,
    "prestigio": 4,
    "propietario": "Libre",
    "coordenadas_x": 37.252671,
    "coordenadas_y": -7.211339,
    "seguridad": 0
  },
  {
    "id": 10,
    "nombre_casa": "Pequeño Refugio",
    "nombre_ciudad": "Lepe",
    "precio": 50000,
    "prestigio": 3,
    "propietario": "Libre",
    "coordenadas_x": 37.253475,
    "coordenadas_y": -7.210493,
    "seguridad": 0
  },
    {
    "id": 1,
    "nombre_casa": "Casa Serenidad",
    "nombre_ciudad": "Cieza",
    "precio": 90000,
    "prestigio": 6,
    "propietario": "Libre",
    "coordenadas_x": 38.238949,
    "coordenadas_y": -1.414330,
    "seguridad": 0
  },
  {
    "id": 2,
    "nombre_casa": "Villa Esmeralda",
    "nombre_ciudad": "Cieza",
    "precio": 120000,
    "prestigio": 8,
    "propietario": "Libre",
    "coordenadas_x": 38.240622,
    "coordenadas_y": -1.414147,
    "seguridad": 0
  },
  {
    "id": 3,
    "nombre_casa": "Refugio del Sol",
    "nombre_ciudad": "Cieza",
    "precio": 60000,
    "prestigio": 4,
    "propietario": "Libre",
    "coordenadas_x": 38.239456,
    "coordenadas_y": -1.414714,
    "seguridad": 0
  },
  {
    "id": 4,
    "nombre_casa": "Quinta Luna",
    "nombre_ciudad": "Cieza",
    "precio": 75000,
    "prestigio": 5,
    "propietario": "Libre",
    "coordenadas_x": 38.238736,
    "coordenadas_y": -1.415023,
    "seguridad": 0
  },
  {
    "id": 5,
    "nombre_casa": "Hogar Dulce Hogar",
    "nombre_ciudad": "Cieza",
    "precio": 80000,
    "prestigio": 5,
    "propietario": "Libre",
    "coordenadas_x": 38.239931,
    "coordenadas_y": -1.414477,
    "seguridad": 0
  },
  {
    "id": 6,
    "nombre_casa": "Casa Encanto",
    "nombre_ciudad": "Cieza",
    "precio": 110000,
    "prestigio": 7,
    "propietario": "Libre",
    "coordenadas_x": 38.240212,
    "coordenadas_y": -1.415048,
    "seguridad": 0
  },
  {
    "id": 7,
    "nombre_casa": "Mansión Aurora",
    "nombre_ciudad": "Cieza",
    "precio": 140000,
    "prestigio": 9,
    "propietario": "Libre",
    "coordenadas_x": 38.240843,
    "coordenadas_y": -1.414278,
    "seguridad": 0
  },
  {
    "id": 8,
    "nombre_casa": "Villa del Sol",
    "nombre_ciudad": "Cieza",
    "precio": 130000,
    "prestigio": 8,
    "propietario": "Libre",
    "coordenadas_x": 38.239674,
    "coordenadas_y": -1.414919,
    "seguridad": 0
  },
  {
    "id": 9,
    "nombre_casa": "Rincón Acogedor",
    "nombre_ciudad": "Cieza",
    "precio": 70000,
    "prestigio": 4,
    "propietario": "Libre",
    "coordenadas_x": 38.239044,
    "coordenadas_y": -1.414647,
    "seguridad": 0
  },
  {
    "id": 10,
    "nombre_casa": "Pequeño Refugio",
    "nombre_ciudad": "Cieza",
    "precio": 50000,
    "prestigio": 3,
    "propietario": "Libre",
    "coordenadas_x": 38.240531,
    "coordenadas_y": -1.415256,
    "seguridad": 0
  },
    {
    "id": 1,
    "nombre_casa": "Casa Serenidad",
    "nombre_ciudad": "Mazarrón",
    "precio": 90000,
    "prestigio": 6,
    "propietario": "Libre",
    "coordenadas_x": 37.594972,
    "coordenadas_y": -1.308045,
    "seguridad": 0
  },
  {
    "id": 2,
    "nombre_casa": "Villa Esmeralda",
    "nombre_ciudad": "Mazarrón",
    "precio": 120000,
    "prestigio": 8,
    "propietario": "Libre",
    "coordenadas_x": 37.595671,
    "coordenadas_y": -1.309554,
    "seguridad": 0
  },
  {
    "id": 3,
    "nombre_casa": "Refugio del Sol",
    "nombre_ciudad": "Mazarrón",
    "precio": 60000,
    "prestigio": 4,
    "propietario": "Libre",
    "coordenadas_x": 37.594582,
    "coordenadas_y": -1.309956,
    "seguridad": 0
  },
  {
    "id": 4,
    "nombre_casa": "Quinta Luna",
    "nombre_ciudad": "Mazarrón",
    "precio": 75000,
    "prestigio": 5,
    "propietario": "Libre",
    "coordenadas_x": 37.595019,
    "coordenadas_y": -1.307825,
    "seguridad": 0
  },
  {
    "id": 5,
    "nombre_casa": "Hogar Dulce Hogar",
    "nombre_ciudad": "Mazarrón",
    "precio": 80000,
    "prestigio": 5,
    "propietario": "Libre",
    "coordenadas_x": 37.594344,
    "coordenadas_y": -1.308759,
    "seguridad": 0
  },
  {
    "id": 6,
    "nombre_casa": "Casa Encanto",
    "nombre_ciudad": "Mazarrón",
    "precio": 110000,
    "prestigio": 7,
    "propietario": "Libre",
    "coordenadas_x": 37.595457,
    "coordenadas_y": -1.309845,
    "seguridad": 0
  },
  {
    "id": 7,
    "nombre_casa": "Mansión Aurora",
    "nombre_ciudad": "Mazarrón",
    "precio": 140000,
    "prestigio": 9,
    "propietario": "Libre",
    "coordenadas_x": 37.594772,
    "coordenadas_y": -1.308381,
    "seguridad": 0
  },
  {
    "id": 8,
    "nombre_casa": "Villa del Sol",
    "nombre_ciudad": "Mazarrón",
    "precio": 130000,
    "prestigio": 8,
    "propietario": "Libre",
    "coordenadas_x": 37.595048,
    "coordenadas_y": -1.309712,
    "seguridad": 0
  },
  {
    "id": 9,
    "nombre_casa": "Rincón Acogedor",
    "nombre_ciudad": "Mazarrón",
    "precio": 70000,
    "prestigio": 4,
    "propietario": "Libre",
    "coordenadas_x": 37.594423,
    "coordenadas_y": -1.309005,
    "seguridad": 0
  },
  {
    "id": 10,
    "nombre_casa": "Pequeño Refugio",
    "nombre_ciudad": "Mazarrón",
    "precio": 50000,
    "prestigio": 3,
    "propietario": "Libre",
    "coordenadas_x": 37.595295,
    "coordenadas_y": -1.309125,
    "seguridad": 0
  },
    {
    "id": 1,
    "nombre_casa": "Casa Serenidad",
    "nombre_ciudad": "Burriana",
    "precio": 90000,
    "prestigio": 6,
    "propietario": "Libre",
    "coordenadas_x": 39.891586,
    "coordenadas_y": -0.084665,
    "seguridad": 0
  },
  {
    "id": 2,
    "nombre_casa": "Villa Esmeralda",
    "nombre_ciudad": "Burriana",
    "precio": 120000,
    "prestigio": 8,
    "propietario": "Libre",
    "coordenadas_x": 39.892374,
    "coordenadas_y": -0.084242,
    "seguridad": 0
  },
  {
    "id": 3,
    "nombre_casa": "Refugio del Sol",
    "nombre_ciudad": "Burriana",
    "precio": 60000,
    "prestigio": 4,
    "propietario": "Libre",
    "coordenadas_x": 39.891731,
    "coordenadas_y": -0.085155,
    "seguridad": 0
  },
  {
    "id": 4,
    "nombre_casa": "Quinta Luna",
    "nombre_ciudad": "Burriana",
    "precio": 75000,
    "prestigio": 5,
    "propietario": "Libre",
    "coordenadas_x": 39.892187,
    "coordenadas_y": -0.083961,
    "seguridad": 0
  },
  {
    "id": 5,
    "nombre_casa": "Hogar Dulce Hogar",
    "nombre_ciudad": "Burriana",
    "precio": 80000,
    "prestigio": 5,
    "propietario": "Libre",
    "coordenadas_x": 39.892895,
    "coordenadas_y": -0.084512,
    "seguridad": 0
  },
  {
    "id": 6,
    "nombre_casa": "Casa Encanto",
    "nombre_ciudad": "Burriana",
    "precio": 110000,
    "prestigio": 7,
    "propietario": "Libre",
    "coordenadas_x": 39.891986,
    "coordenadas_y": -0.083999,
    "seguridad": 0
  },
  {
    "id": 7,
    "nombre_casa": "Mansión Aurora",
    "nombre_ciudad": "Burriana",
    "precio": 140000,
    "prestigio": 9,
    "propietario": "Libre",
    "coordenadas_x": 39.892428,
    "coordenadas_y": -0.085012,
    "seguridad": 0
  },
  {
    "id": 8,
    "nombre_casa": "Villa del Sol",
    "nombre_ciudad": "Burriana",
    "precio": 130000,
    "prestigio": 8,
    "propietario": "Libre",
    "coordenadas_x": 39.891473,
    "coordenadas_y": -0.083903,
    "seguridad": 0
  },
  {
    "id": 9,
    "nombre_casa": "Rincón Acogedor",
    "nombre_ciudad": "Burriana",
    "precio": 70000,
    "prestigio": 4,
    "propietario": "Libre",
    "coordenadas_x": 39.892674,
    "coordenadas_y": -0.084993,
    "seguridad": 0
  },
  {
    "id": 10,
    "nombre_casa": "Pequeño Refugio",
    "nombre_ciudad": "Burriana",
    "precio": 50000,
    "prestigio": 3,
    "propietario": "Libre",
    "coordenadas_x": 39.892017,
    "coordenadas_y": -0.085312,
    "seguridad": 0
  },
    {
    "id": 1,
    "nombre_casa": "Casa Serenidad",
    "nombre_ciudad": "Carcaixent",
    "precio": 90000,
    "prestigio": 6,
    "propietario": "Libre",
    "coordenadas_x": 39.119531,
    "coordenadas_y": -0.453181,
    "seguridad": 0
  },
  {
    "id": 2,
    "nombre_casa": "Villa Esmeralda",
    "nombre_ciudad": "Carcaixent",
    "precio": 120000,
    "prestigio": 8,
    "propietario": "Libre",
    "coordenadas_x": 39.118862,
    "coordenadas_y": -0.452678,
    "seguridad": 0
  },
  {
    "id": 3,
    "nombre_casa": "Refugio del Sol",
    "nombre_ciudad": "Carcaixent",
    "precio": 60000,
    "prestigio": 4,
    "propietario": "Libre",
    "coordenadas_x": 39.120245,
    "coordenadas_y": -0.452370,
    "seguridad": 0
  },
  {
    "id": 4,
    "nombre_casa": "Quinta Luna",
    "nombre_ciudad": "Carcaixent",
    "precio": 75000,
    "prestigio": 5,
    "propietario": "Libre",
    "coordenadas_x": 39.119879,
    "coordenadas_y": -0.454073,
    "seguridad": 0
  },
  {
    "id": 5,
    "nombre_casa": "Hogar Dulce Hogar",
    "nombre_ciudad": "Carcaixent",
    "precio": 80000,
    "prestigio": 5,
    "propietario": "Libre",
    "coordenadas_x": 39.119143,
    "coordenadas_y": -0.454176,
    "seguridad": 0
  },
  {
    "id": 6,
    "nombre_casa": "Casa Encanto",
    "nombre_ciudad": "Carcaixent",
    "precio": 110000,
    "prestigio": 7,
    "propietario": "Libre",
    "coordenadas_x": 39.118755,
    "coordenadas_y": -0.454002,
    "seguridad": 0
  },
  {
    "id": 7,
    "nombre_casa": "Mansión Aurora",
    "nombre_ciudad": "Carcaixent",
    "precio": 140000,
    "prestigio": 9,
    "propietario": "Libre",
    "coordenadas_x": 39.120193,
    "coordenadas_y": -0.454241,
    "seguridad": 0
  },
  {
    "id": 8,
    "nombre_casa": "Villa del Sol",
    "nombre_ciudad": "Carcaixent",
    "precio": 130000,
    "prestigio": 8,
    "propietario": "Libre",
    "coordenadas_x": 39.119485,
    "coordenadas_y": -0.453677,
    "seguridad": 0
  },
  {
    "id": 9,
    "nombre_casa": "Rincón Acogedor",
    "nombre_ciudad": "Carcaixent",
    "precio": 70000,
    "prestigio": 4,
    "propietario": "Libre",
    "coordenadas_x": 39.118963,
    "coordenadas_y": -0.453685,
    "seguridad": 0
  },
  {
    "id": 10,
    "nombre_casa": "Pequeño Refugio",
    "nombre_ciudad": "Carcaixent",
    "precio": 50000,
    "prestigio": 3,
    "propietario": "Libre",
    "coordenadas_x": 39.119623,
    "coordenadas_y": -0.453180,
    "seguridad": 0
  },
    {
    "id": 1,
    "nombre_casa": "Casa Serenidad",
    "nombre_ciudad": "Caravaca de la Cruz",
    "precio": 90000,
    "prestigio": 6,
    "propietario": "Libre",
    "coordenadas_x": 38.099325,
    "coordenadas_y": -1.857734,
    "seguridad": 0
  },
  {
    "id": 2,
    "nombre_casa": "Villa Esmeralda",
    "nombre_ciudad": "Caravaca de la Cruz",
    "precio": 120000,
    "prestigio": 8,
    "propietario": "Libre",
    "coordenadas_x": 38.098946,
    "coordenadas_y": -1.857468,
    "seguridad": 0
  },
  {
    "id": 3,
    "nombre_casa": "Refugio del Sol",
    "nombre_ciudad": "Caravaca de la Cruz",
    "precio": 60000,
    "prestigio": 4,
    "propietario": "Libre",
    "coordenadas_x": 38.099671,
    "coordenadas_y": -1.857967,
    "seguridad": 0
  },
  {
    "id": 4,
    "nombre_casa": "Quinta Luna",
    "nombre_ciudad": "Caravaca de la Cruz",
    "precio": 75000,
    "prestigio": 5,
    "propietario": "Libre",
    "coordenadas_x": 38.099064,
    "coordenadas_y": -1.857592,
    "seguridad": 0
  },
  {
    "id": 5,
    "nombre_casa": "Hogar Dulce Hogar",
    "nombre_ciudad": "Caravaca de la Cruz",
    "precio": 80000,
    "prestigio": 5,
    "propietario": "Libre",
    "coordenadas_x": 38.099535,
    "coordenadas_y": -1.857883,
    "seguridad": 0
  },
  {
    "id": 6,
    "nombre_casa": "Casa Encanto",
    "nombre_ciudad": "Caravaca de la Cruz",
    "precio": 110000,
    "prestigio": 7,
    "propietario": "Libre",
    "coordenadas_x": 38.098692,
    "coordenadas_y": -1.857729,
    "seguridad": 0
  },
  {
    "id": 7,
    "nombre_casa": "Mansión Aurora",
    "nombre_ciudad": "Caravaca de la Cruz",
    "precio": 140000,
    "prestigio": 9,
    "propietario": "Libre",
    "coordenadas_x": 38.099832,
    "coordenadas_y": -1.857959,
    "seguridad": 0
  },
  {
    "id": 8,
    "nombre_casa": "Villa del Sol",
    "nombre_ciudad": "Caravaca de la Cruz",
    "precio": 130000,
    "prestigio": 8,
    "propietario": "Libre",
    "coordenadas_x": 38.098961,
    "coordenadas_y": -1.857857,
    "seguridad": 0
  },
  {
    "id": 9,
    "nombre_casa": "Rincón Acogedor",
    "nombre_ciudad": "Caravaca de la Cruz",
    "precio": 70000,
    "prestigio": 4,
    "propietario": "Libre",
    "coordenadas_x": 38.098822,
    "coordenadas_y": -1.857581,
    "seguridad": 0
  },
  {
    "id": 10,
    "nombre_casa": "Pequeño Refugio",
    "nombre_ciudad": "Caravaca de la Cruz",
    "precio": 50000,
    "prestigio": 3,
    "propietario": "Libre",
    "coordenadas_x": 38.099349,
    "coordenadas_y": -1.857416,
    "seguridad": 0
  },
    {
    "id": 1,
    "nombre_casa": "Casa Serenidad",
    "nombre_ciudad": "Palencia",
    "precio": 80000,
    "prestigio": 6,
    "propietario": "Libre",
    "coordenadas_x": 42.004646,
    "coordenadas_y": -4.533214,
    "seguridad": 0
  },
  {
    "id": 2,
    "nombre_casa": "Villa Esmeralda",
    "nombre_ciudad": "Palencia",
    "precio": 120000,
    "prestigio": 8,
    "propietario": "Libre",
    "coordenadas_x": 42.001380,
    "coordenadas_y": -4.534108,
    "seguridad": 0
  },
  {
    "id": 3,
    "nombre_casa": "Refugio del Sol",
    "nombre_ciudad": "Palencia",
    "precio": 60000,
    "prestigio": 4,
    "propietario": "Libre",
    "coordenadas_x": 42.002951,
    "coordenadas_y": -4.531816,
    "seguridad": 0
  },
  {
    "id": 4,
    "nombre_casa": "Quinta Luna",
    "nombre_ciudad": "Palencia",
    "precio": 70000,
    "prestigio": 5,
    "propietario": "Libre",
    "coordenadas_x": 42.005654,
    "coordenadas_y": -4.530287,
    "seguridad": 0
  },
  {
    "id": 5,
    "nombre_casa": "Hogar Dulce Hogar",
    "nombre_ciudad": "Palencia",
    "precio": 90000,
    "prestigio": 5,
    "propietario": "Libre",
    "coordenadas_x": 42.003906,
    "coordenadas_y": -4.532699,
    "seguridad": 0
  },
  {
    "id": 6,
    "nombre_casa": "Casa Encanto",
    "nombre_ciudad": "Palencia",
    "precio": 110000,
    "prestigio": 7,
    "propietario": "Libre",
    "coordenadas_x": 42.005419,
    "coordenadas_y": -4.534729,
    "seguridad": 0
  },
  {
    "id": 7,
    "nombre_casa": "Mansión Aurora",
    "nombre_ciudad": "Palencia",
    "precio": 140000,
    "prestigio": 9,
    "propietario": "Libre",
    "coordenadas_x": 42.003521,
    "coordenadas_y": -4.534911,
    "seguridad": 0
  },
  {
    "id": 8,
    "nombre_casa": "Villa del Sol",
    "nombre_ciudad": "Palencia",
    "precio": 130000,
    "prestigio": 8,
    "propietario": "Libre",
    "coordenadas_x": 42.004286,
    "coordenadas_y": -4.531139,
    "seguridad": 0
  },
  {
    "id": 9,
    "nombre_casa": "Rincón Acogedor",
    "nombre_ciudad": "Palencia",
    "precio": 70000,
    "prestigio": 4,
    "propietario": "Libre",
    "coordenadas_x": 42.002160,
    "coordenadas_y": -4.530452,
    "seguridad": 0
  },
  {
    "id": 10,
    "nombre_casa": "Pequeño Refugio",
    "nombre_ciudad": "Palencia",
    "precio": 50000,
    "prestigio": 3,
    "propietario": "Libre",
    "coordenadas_x": 42.005170,
    "coordenadas_y": -4.531602,
    "seguridad": 0
  },
    {
    "id": 1,
    "nombre_casa": "Casa Serenidad",
    "nombre_ciudad": "Soto del Real",
    "precio": 90000,
    "prestigio": 6,
    "propietario": "Libre",
    "coordenadas_x": 40.747927,
    "coordenadas_y": -3.719440,
    "seguridad": 0
  },
  {
    "id": 2,
    "nombre_casa": "Villa Esmeralda",
    "nombre_ciudad": "Soto del Real",
    "precio": 120000,
    "prestigio": 8,
    "propietario": "Libre",
    "coordenadas_x": 40.748336,
    "coordenadas_y": -3.719025,
    "seguridad": 0
  },
  {
    "id": 3,
    "nombre_casa": "Refugio del Sol",
    "nombre_ciudad": "Soto del Real",
    "precio": 60000,
    "prestigio": 4,
    "propietario": "Libre",
    "coordenadas_x": 40.748743,
    "coordenadas_y": -3.719835,
    "seguridad": 0
  },
  {
    "id": 4,
    "nombre_casa": "Quinta Luna",
    "nombre_ciudad": "Soto del Real",
    "precio": 70000,
    "prestigio": 5,
    "propietario": "Libre",
    "coordenadas_x": 40.749152,
    "coordenadas_y": -3.719421,
    "seguridad": 0
  },
  {
    "id": 5,
    "nombre_casa": "Hogar Dulce Hogar",
    "nombre_ciudad": "Soto del Real",
    "precio": 80000,
    "prestigio": 5,
    "propietario": "Libre",
    "coordenadas_x": 40.749561,
    "coordenadas_y": -3.719007,
    "seguridad": 0
  },
  {
    "id": 6,
    "nombre_casa": "Casa Encanto",
    "nombre_ciudad": "Soto del Real",
    "precio": 110000,
    "prestigio": 7,
    "propietario": "Libre",
    "coordenadas_x": 40.750374,
    "coordenadas_y": -3.718179,
    "seguridad": 0
  },
  {
    "id": 7,
    "nombre_casa": "Mansión Aurora",
    "nombre_ciudad": "Soto del Real",
    "precio": 140000,
    "prestigio": 9,
    "propietario": "Libre",
    "coordenadas_x": 40.750783,
    "coordenadas_y": -3.717765,
    "seguridad": 0
  },
  {
    "id": 8,
    "nombre_casa": "Villa del Sol",
    "nombre_ciudad": "Soto del Real",
    "precio": 130000,
    "prestigio": 8,
    "propietario": "Libre",
    "coordenadas_x": 40.751192,
    "coordenadas_y": -3.717351,
    "seguridad": 0
  },
  {
    "id": 9,
    "nombre_casa": "Rincón Acogedor",
    "nombre_ciudad": "Soto del Real",
    "precio": 70000,
    "prestigio": 4,
    "propietario": "Libre",
    "coordenadas_x": 40.751600,
    "coordenadas_y": -3.716938,
    "seguridad": 0
  },
  {
    "id": 10,
    "nombre_casa": "Pequeño Refugio",
    "nombre_ciudad": "Soto del Real",
    "precio": 50000,
    "prestigio": 3,
    "propietario": "Libre",
    "coordenadas_x": 40.752009,
    "coordenadas_y": -3.716524,
    "seguridad": 0
  },
    {
    "id": 1,
    "nombre_casa": "Casa Serenidad",
    "nombre_ciudad": "Girona",
    "precio": 80000,
    "prestigio": 6,
    "propietario": "Libre",
    "coordenadas_x": 41.980954,
    "coordenadas_y": 2.823934,
    "seguridad": 0
  },
  {
    "id": 2,
    "nombre_casa": "Villa Esmeralda",
    "nombre_ciudad": "Girona",
    "precio": 120000,
    "prestigio": 8,
    "propietario": "Libre",
    "coordenadas_x": 41.975643,
    "coordenadas_y": 2.826152,
    "seguridad": 0
  },
  {
    "id": 3,
    "nombre_casa": "Refugio del Sol",
    "nombre_ciudad": "Girona",
    "precio": 60000,
    "prestigio": 4,
    "propietario": "Libre",
    "coordenadas_x": 41.981749,
    "coordenadas_y": 2.820943,
    "seguridad": 0
  },
  {
    "id": 4,
    "nombre_casa": "Quinta Luna",
    "nombre_ciudad": "Girona",
    "precio": 70000,
    "prestigio": 5,
    "propietario": "Libre",
    "coordenadas_x": 41.979146,
    "coordenadas_y": 2.824533,
    "seguridad": 0
  },
  {
    "id": 5,
    "nombre_casa": "Hogar Dulce Hogar",
    "nombre_ciudad": "Girona",
    "precio": 90000,
    "prestigio": 5,
    "propietario": "Libre",
    "coordenadas_x": 41.980322,
    "coordenadas_y": 2.819345,
    "seguridad": 0
  },
  {
    "id": 6,
    "nombre_casa": "Casa Encanto",
    "nombre_ciudad": "Girona",
    "precio": 110000,
    "prestigio": 7,
    "propietario": "Libre",
    "coordenadas_x": 41.977987,
    "coordenadas_y": 2.824721,
    "seguridad": 0
  },
  {
    "id": 7,
    "nombre_casa": "Mansión Aurora",
    "nombre_ciudad": "Girona",
    "precio": 140000,
    "prestigio": 9,
    "propietario": "Libre",
    "coordenadas_x": 41.976820,
    "coordenadas_y": 2.820388,
    "seguridad": 0
  },
  {
    "id": 8,
    "nombre_casa": "Villa del Sol",
    "nombre_ciudad": "Girona",
    "precio": 130000,
    "prestigio": 8,
    "propietario": "Libre",
    "coordenadas_x": 41.981456,
    "coordenadas_y": 2.822786,
    "seguridad": 0
  },
  {
    "id": 9,
    "nombre_casa": "Rincón Acogedor",
    "nombre_ciudad": "Girona",
    "precio": 70000,
    "prestigio": 4,
    "propietario": "Libre",
    "coordenadas_x": 41.977208,
    "coordenadas_y": 2.821570,
    "seguridad": 0
  },
  {
    "id": 10,
    "nombre_casa": "Pequeño Refugio",
    "nombre_ciudad": "Girona",
    "precio": 50000,
    "prestigio": 3,
    "propietario": "Libre",
    "coordenadas_x": 41.981134,
    "coordenadas_y": 2.819878,
    "seguridad": 0
  },
    {
    "id": 1,
    "nombre_casa": "Casa Serenidad",
    "nombre_ciudad": "Tortosa",
    "precio": 90000,
    "prestigio": 6,
    "propietario": "Libre",
    "coordenadas_x": 40.812830,
    "coordenadas_y": 0.520180,
    "seguridad": 0
  },
  {
    "id": 2,
    "nombre_casa": "Villa Esmeralda",
    "nombre_ciudad": "Tortosa",
    "precio": 120000,
    "prestigio": 8,
    "propietario": "Libre",
    "coordenadas_x": 40.816203,
    "coordenadas_y": 0.520625,
    "seguridad": 0
  },
  {
    "id": 3,
    "nombre_casa": "Refugio del Sol",
    "nombre_ciudad": "Tortosa",
    "precio": 60000,
    "prestigio": 4,
    "propietario": "Libre",
    "coordenadas_x": 40.811719,
    "coordenadas_y": 0.518904,
    "seguridad": 0
  },
  {
    "id": 4,
    "nombre_casa": "Quinta Luna",
    "nombre_ciudad": "Tortosa",
    "precio": 70000,
    "prestigio": 5,
    "propietario": "Libre",
    "coordenadas_x": 40.814185,
    "coordenadas_y": 0.517184,
    "seguridad": 0
  },
  {
    "id": 5,
    "nombre_casa": "Hogar Dulce Hogar",
    "nombre_ciudad": "Tortosa",
    "precio": 80000,
    "prestigio": 5,
    "propietario": "Libre",
    "coordenadas_x": 40.812064,
    "coordenadas_y": 0.519698,
    "seguridad": 0
  },
  {
    "id": 6,
    "nombre_casa": "Casa Encanto",
    "nombre_ciudad": "Tortosa",
    "precio": 110000,
    "prestigio": 7,
    "propietario": "Libre",
    "coordenadas_x": 40.815636,
    "coordenadas_y": 0.518127,
    "seguridad": 0
  },
  {
    "id": 7,
    "nombre_casa": "Mansión Aurora",
    "nombre_ciudad": "Tortosa",
    "precio": 140000,
    "prestigio": 9,
    "propietario": "Libre",
    "coordenadas_x": 40.813508,
    "coordenadas_y": 0.516408,
    "seguridad": 0
  },
  {
    "id": 8,
    "nombre_casa": "Villa del Sol",
    "nombre_ciudad": "Tortosa",
    "precio": 130000,
    "prestigio": 8,
    "propietario": "Libre",
    "coordenadas_x": 40.817017,
    "coordenadas_y": 0.517853,
    "seguridad": 0
  },
  {
    "id": 9,
    "nombre_casa": "Rincón Acogedor",
    "nombre_ciudad": "Tortosa",
    "precio": 70000,
    "prestigio": 4,
    "propietario": "Libre",
    "coordenadas_x": 40.814753,
    "coordenadas_y": 0.519219,
    "seguridad": 0
  },
  {
    "id": 10,
    "nombre_casa": "Pequeño Refugio",
    "nombre_ciudad": "Tortosa",
    "precio": 50000,
    "prestigio": 3,
    "propietario": "Libre",
    "coordenadas_x": 40.810979,
    "coordenadas_y": 0.517639,
    "seguridad": 0
  },
    {
    "id": 1,
    "nombre_casa": "Casa Serenidad",
    "nombre_ciudad": "Baza",
    "precio": 60000,
    "prestigio": 4,
    "propietario": "Libre",
    "coordenadas_x": 37.496080,
    "coordenadas_y": -2.768212,
    "seguridad": 0
  },
  {
    "id": 2,
    "nombre_casa": "Villa Esmeralda",
    "nombre_ciudad": "Baza",
    "precio": 100000,
    "prestigio": 7,
    "propietario": "Libre",
    "coordenadas_x": 37.486492,
    "coordenadas_y": -2.777998,
    "seguridad": 0
  },
  {
    "id": 3,
    "nombre_casa": "Refugio del Sol",
    "nombre_ciudad": "Baza",
    "precio": 45000,
    "prestigio": 3,
    "propietario": "Libre",
    "coordenadas_x": 37.489768,
    "coordenadas_y": -2.777087,
    "seguridad": 0
  },
  {
    "id": 4,
    "nombre_casa": "Quinta Luna",
    "nombre_ciudad": "Baza",
    "precio": 55000,
    "prestigio": 4,
    "propietario": "Libre",
    "coordenadas_x": 37.493240,
    "coordenadas_y": -2.765879,
    "seguridad": 0
  },
  {
    "id": 5,
    "nombre_casa": "Hogar Dulce Hogar",
    "nombre_ciudad": "Baza",
    "precio": 70000,
    "prestigio": 5,
    "propietario": "Libre",
    "coordenadas_x": 37.498603,
    "coordenadas_y": -2.774409,
    "seguridad": 0
  },
  {
    "id": 6,
    "nombre_casa": "Casa Encanto",
    "nombre_ciudad": "Baza",
    "precio": 85000,
    "prestigio": 6,
    "propietario": "Libre",
    "coordenadas_x": 37.496819,
    "coordenadas_y": -2.769938,
    "seguridad": 0
  },
  {
    "id": 7,
    "nombre_casa": "Mansión Aurora",
    "nombre_ciudad": "Baza",
    "precio": 120000,
    "prestigio": 8,
    "propietario": "Libre",
    "coordenadas_x": 37.485726,
    "coordenadas_y": -2.769641,
    "seguridad": 0
  },
  {
    "id": 8,
    "nombre_casa": "Villa del Sol",
    "nombre_ciudad": "Baza",
    "precio": 110000,
    "prestigio": 7,
    "propietario": "Libre",
    "coordenadas_x": 37.491935,
    "coordenadas_y": -2.773732,
    "seguridad": 0
  },
  {
    "id": 9,
    "nombre_casa": "Rincón Acogedor",
    "nombre_ciudad": "Baza",
    "precio": 50000,
    "prestigio": 3,
    "propietario": "Libre",
    "coordenadas_x": 37.497287,
    "coordenadas_y": -2.772836,
    "seguridad": 0
  },
  {
    "id": 10,
    "nombre_casa": "Pequeño Refugio",
    "nombre_ciudad": "Baza",
    "precio": 40000,
    "prestigio": 2,
    "propietario": "Libre",
    "coordenadas_x": 37.494961,
    "coordenadas_y": -2.776314,
    "seguridad": 0
  },
  {
        "id": 1,
        "nombre_casa": "Casa Serenidad",
        "nombre_ciudad": "Candeleda",
        "precio": 90000,
        "prestigio": 6,
        "propietario": "Libre",
        "coordenadas_x": 40.236597,
        "coordenadas_y": -5.315697,
        "seguridad": 0
    },
    {
        "id": 2,
        "nombre_casa": "Villa Esmeralda",
        "nombre_ciudad": "Candeleda",
        "precio": 120000,
        "prestigio": 7,
        "propietario": "Libre",
        "coordenadas_x": 40.236981,
        "coordenadas_y": -5.317832,
        "seguridad": 0
    },
    {
        "id": 3,
        "nombre_casa": "Refugio del Sol",
        "nombre_ciudad": "Candeleda",
        "precio": 75000,
        "prestigio": 5,
        "propietario": "Libre",
        "coordenadas_x": 40.237419,
        "coordenadas_y": -5.319473,
        "seguridad": 0
    },
    {
        "id": 4,
        "nombre_casa": "Quinta Luna",
        "nombre_ciudad": "Candeleda",
        "precio": 80000,
        "prestigio": 5,
        "propietario": "Libre",
        "coordenadas_x": 40.238572,
        "coordenadas_y": -5.318651,
        "seguridad": 0
    },
    {
        "id": 5,
        "nombre_casa": "Hogar Dulce Hogar",
        "nombre_ciudad": "Candeleda",
        "precio": 100000,
        "prestigio": 6,
        "propietario": "Libre",
        "coordenadas_x": 40.236324,
        "coordenadas_y": -5.320971,
        "seguridad": 0
    },
    {
        "id": 6,
        "nombre_casa": "Casa Encanto",
        "nombre_ciudad": "Candeleda",
        "precio": 110000,
        "prestigio": 7,
        "propietario": "Libre",
        "coordenadas_x": 40.239610,
        "coordenadas_y": -5.316886,
        "seguridad": 0
    },
    {
        "id": 7,
        "nombre_casa": "Mansión Aurora",
        "nombre_ciudad": "Candeleda",
        "precio": 150000,
        "prestigio": 10,
        "propietario": "Libre",
        "coordenadas_x": 40.235841,
        "coordenadas_y": -5.319138,
        "seguridad": 0
    },
    {
        "id": 8,
        "nombre_casa": "Villa del Sol",
        "nombre_ciudad": "Candeleda",
        "precio": 140000,
        "prestigio": 9,
        "propietario": "Libre",
        "coordenadas_x": 40.239016,
        "coordenadas_y": -5.315736,
        "seguridad": 0
    },
    {
        "id": 9,
        "nombre_casa": "Rincón Acogedor",
        "nombre_ciudad": "Candeleda",
        "precio": 70000,
        "prestigio": 4,
        "propietario": "Libre",
        "coordenadas_x": 40.238818,
        "coordenadas_y": -5.320327,
        "seguridad": 0
    },
    {
        "id": 10,
        "nombre_casa": "Pequeño Refugio",
        "nombre_ciudad": "Candeleda",
        "precio": 60000,
        "prestigio": 3,
        "propietario": "Libre",
        "coordenadas_x": 40.239755,
        "coordenadas_y": -5.319727,
        "seguridad": 0
    }
    ]
db = DatabaseManager(pathBBDD)
db.insert_enpleadoselectronica(empleados)
